USE general;

CREATE TABLE `locations` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `zh_name` varchar(100) NOT NULL DEFAULT '',
  `en_name` varchar(100) NOT NULL DEFAULT '',
  `created_dt` datetime DEFAULT NULL,
  `updated_dt` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `zh_name` (`zh_name`,`en_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tags` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `zh_name` varchar(50) NOT NULL DEFAULT '',
  `en_name` varchar(50) NOT NULL DEFAULT '',
  `created_dt` datetime DEFAULT NULL,
  `updated_dt` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `zh_name` (`zh_name`,`en_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `restaurants` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `location_id` int(11) NOT NULL,
  `name` varchar(100) NOT NULL DEFAULT '',
  `zh_address` varchar(200) NOT NULL DEFAULT '',
  `en_address` varchar(200) NOT NULL DEFAULT '',
  `price_from` decimal(10,2) NOT NULL,
  `price_to` decimal(10,2) NOT NULL,
  `created_dt` datetime DEFAULT NULL,
  `updated_dt` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `location_id` (`location_id`),
  KEY `name` (`name`),
  KEY `price_from` (`price_from`,`price_to`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `restaurant_links` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `restaurant_id` int(11) NOT NULL,
  `link` text NOT NULL,
  `type` varchar(50) NOT NULL DEFAULT '',
  `created_dt` datetime DEFAULT NULL,
  `updated_dt` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `restaurant_tags` (
  `id` bigint(11) unsigned NOT NULL AUTO_INCREMENT,
  `restaurant_id` int(11) NOT NULL,
  `tag_id` int(11) NOT NULL,
  `created_dt` datetime DEFAULT NULL,
  `updated_dt` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `locations` (`zh_name`,`en_name`,`created_dt`,`updated_dt`) VALUES
('九龍城','Kowloon city',NOW(),NOW()),
('九龍塘','Kowloon Tong',NOW(),NOW()),
('九龍灣','Kowloon Bay',NOW(),NOW()),
('上水','Sheung Shui',NOW(),NOW()),
('上環','Sheung Wan',NOW(),NOW()),
('土瓜灣','To Kwa Wan',NOW(),NOW()),
('大水坑','Tai Shui Hang',NOW(),NOW()),
('大角咀','Tai Kok Tsui',NOW(),NOW()),
('大埔','Tai Po',NOW(),NOW()),
('大圍','Tai Wai',NOW(),NOW()),
('大窩口','Tai Wo Hau',NOW(),NOW()),
('大嶼山','Lantao Island',NOW(),NOW()),
('中環','Central',NOW(),NOW()),
('元朗','Yuen Long',NOW(),NOW()),
('友愛','Yau Oi',NOW(),NOW()),
('天水圍','Tin Shui Wai',NOW(),NOW()),
('天后','Tin Hau',NOW(),NOW()),
('太子','Prince Edward',NOW(),NOW()),
('太古','Tai Koo',NOW(),NOW()),
('太和','Tai Wo',NOW(),NOW()),
('屯門','Tuen Mun',NOW(),NOW()),
('屯門中心','Tuen Mun Centre',NOW(),NOW()),
('火炭','Fo Tan',NOW(),NOW()),
('牛頭角','Ngau Tau Kok',NOW(),NOW()),
('北角','North Point',NOW(),NOW()),
('坪洲','Peng Chau',NOW(),NOW()),
('石門','Shek Mun',NOW(),NOW()),
('石硤尾','Shek Kip Mei',NOW(),NOW()),
('石塘咀','Shek Tong Tsui',NOW(),NOW()),
('兆康','Siu Hong',NOW(),NOW()),
('尖沙咀','Tsim Sha Tsui',NOW(),NOW()),
('西貢','Sai Kung',NOW(),NOW()),
('西營盤','Sai Ying Pun',NOW(),NOW()),
('西灣河','Sai Wan Ho',NOW(),NOW()),
('佐敦','Jordan',NOW(),NOW()),
('何文田','Ho Man Tin',NOW(),NOW()),
('利東','Lei Tung',NOW(),NOW()),
('坑口','Hang Hau',NOW(),NOW()),
('杏花村','Heng Fa Chuen',NOW(),NOW()),
('沙田','Sha Tin',NOW(),NOW()),
('秀茂坪','Sau Mau Ping',NOW(),NOW()),
('良景','Leung King',NOW(),NOW()),
('旺角','Mong Kok',NOW(),NOW()),
('東涌','Tung Chung',NOW(),NOW()),
('油麻地','Yau Ma Tei',NOW(),NOW()),
('油塘','Yau Tong',NOW(),NOW()),
('金鐘','Admiralty',NOW(),NOW()),
('長沙灣','Cheung Sha Wan',NOW(),NOW()),
('長洲','Cheung Chau',NOW(),NOW()),
('青衣','Tsing Yi',NOW(),NOW()),
('炮台山','Fortress Hill',NOW(),NOW()),
('紅磡','Hung Hom',NOW(),NOW()),
('美孚','Mei Foo',NOW(),NOW()),
('朗屏','Long Ping',NOW(),NOW()),
('柴灣','Chai Wan',NOW(),NOW()),
('海怡','South Horizons',NOW(),NOW()),
('粉嶺','Fanling',NOW(),NOW()),
('荃灣','Tsuen Wan',NOW(),NOW()),
('荔枝角','Lai Chi Kok',NOW(),NOW()),
('荔景','Lai King',NOW(),NOW()),
('馬鞍山','Ma On Shan',NOW(),NOW()),
('堅尼地城','Kennedy Town',NOW(),NOW()),
('將軍澳','Tseung Kwan O',NOW(),NOW()),
('康城','LOHAS Park',NOW(),NOW()),
('彩虹','Choi Hung',NOW(),NOW()),
('深水埗','Sham Shui Po',NOW(),NOW()),
('第一城','City One Shatin',NOW(),NOW()),
('黃大仙','Wong Tai Sin',NOW(),NOW()),
('黃竹坑','Wong Chuk Hang',NOW(),NOW()),
('黃埔','Whampoa',NOW(),NOW()),
('新蒲崗','San Po Kong',NOW(),NOW()),
('筲箕灣','Shau Kei Wan',NOW(),NOW()),
('葵芳','Kwai Fong',NOW(),NOW()),
('葵涌','Kwai Chung',NOW(),NOW()),
('葵興','Kwai Hing',NOW(),NOW()),
('慈雲山','Tsz Wan Shan',NOW(),NOW()),
('銅鑼灣','Causeway Bay',NOW(),NOW()),
('樂富','Lok Fu',NOW(),NOW()),
('調景嶺','Tiu Keng Leng',NOW(),NOW()),
('錦上路','Kam Sheung Road',NOW(),NOW()),
('鴨脷洲','Ap Lei Chau',NOW(),NOW()),
('薄扶林','Pok Fu Lam',NOW(),NOW()),
('藍田','Lam Tin',NOW(),NOW()),
('鯉魚門','Lei Yue Mun',NOW(),NOW()),
('寶琳','Po Lam',NOW(),NOW()),
('鰂魚涌','Quarry Bay',NOW(),NOW()),
('灣仔','Wan Chai',NOW(),NOW()),
('觀塘','Kwun Tong',NOW(),NOW()),
('鑽石山','Diamond Hill',NOW(),NOW()),
('禾輋','Wo Che',NOW(),NOW()),
('烏溪沙','Wu Kai Sha',NOW(),NOW()),
('深井','Sham Tseng',NOW(),NOW());